name: CI/CD Pipeline

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  # 1) JOB : Lint + tests + coverage
  build-and-test:
    name: Build and Test (Lint + Coverage)
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Linting (flake8)
        run: |
          echo "Running flake8..."
          flake8 .
        # Si flake8 trouve des erreurs, le job échouera

      - name: Run tests with coverage
        run: |
          echo "Running pytest with coverage..."
          coverage run -m pytest

      - name: Coverage report (fail if coverage < 80%)
        run: coverage report --fail-under=80

  # 2) JOB : Conteneurisation (build + push Docker), uniquement sur main
  containerise:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [build-and-test]

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        # DOCKER_USERNAME et DOCKER_PASSWORD sont stockés comme "secrets" GitHub

      - name: Build Docker image
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)   # pour tagguer avec le hash court
          docker build -t ${{ secrets.DOCKER_USERNAME }}/oc-lettings:${COMMIT_HASH} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/oc-lettings:${COMMIT_HASH} ${{ secrets.DOCKER_USERNAME }}/oc-lettings:latest

      - name: Push Docker image
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker push ${{ secrets.DOCKER_USERNAME }}/oc-lettings:${COMMIT_HASH}
          docker push ${{ secrets.DOCKER_USERNAME }}/oc-lettings:latest

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [containerise]

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering deployment on Render..."
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
                  "serviceId": "'"$RENDER_SERVICE_ID"'",
                  "clearCache": false
                }' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
          echo "Deployment triggered on Render."

